extends SceneTree

# CI visual check for the actual full GridMap district generated by build_road_city_gridmap.gd.
const OUT_DIR := "res://build/road_pilot"
const SCREEN := "res://build/road_pilot/road_pilot_topdown.png"
const REPORT := "res://build/road_pilot/road_pilot_memory_report.txt"
const WIDTH := 1280
const HEIGHT := 720
const DISTRICT := "res://roads/generated/district_01_roads.tscn"

func _initialize() -> void:
    DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
    var scene: PackedScene = load(DISTRICT)
    if scene == null:
        push_error("ROAD PILOT FAIL: missing full district scene")
        quit(2)
        return
    var window: Window = get_root()
    window.size = Vector2i(WIDTH, HEIGHT)
    window.visible = true
    var root := Node3D.new()
    root.name = "RoadFullCapture"
    window.add_child(root)
    var world := WorldEnvironment.new()
    var env := Environment.new()
    env.background_mode = Environment.BG_COLOR
    env.background_color = Color("#87a8b8")
    env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
    env.ambient_light_color = Color.WHITE
    env.ambient_light_energy = 0.9
    world.environment = env
    root.add_child(world)
    var sun := DirectionalLight3D.new()
    sun.rotation_degrees = Vector3(-55.0, -25.0, 0.0)
    sun.light_energy = 1.1
    root.add_child(sun)
    var district := scene.instantiate()
    root.add_child(district)
    var camera := Camera3D.new()
    camera.name = "RoadFullTopDownCamera"
    camera.position = Vector3(-800.0, 95.0, -650.0)
    camera.look_at_from_position(camera.position, Vector3(-800.0, 0.0, -650.0), Vector3(0,0,-1))
    camera.fov = 58.0
    camera.far = 1000.0
    camera.current = true
    root.add_child(camera)
    await process_frame
    await process_frame
    await process_frame
    await process_frame
    await process_frame
    var image: Image = window.get_texture().get_image()
    if image == null or image.is_empty():
        push_error("ROAD PILOT FAIL: rendered image is empty")
        quit(3)
        return
    var save_error := image.save_png(SCREEN)
    if save_error != OK:
        push_error("ROAD PILOT FAIL: PNG save error %s" % save_error)
        quit(4)
        return
    var static_mem := Performance.get_monitor(Performance.MEMORY_STATIC)
    var report := "ROMA ROADS PILOT MEMORY\nGridMap cell=4x0.15x4\nMeshLibrary items=25\nCapture=district_01 full GridMap\nStatic memory after load=%d bytes (%.2f MB)\nTarget additional memory < 50 MB\nNOTE: this is a CI smoke measurement, not a device RSS measurement.\n" % [int(static_mem), float(static_mem) / 1048576.0]
    var file := FileAccess.open(REPORT, FileAccess.WRITE)
    if file == null:
        push_error("ROAD PILOT FAIL: cannot open memory report")
        quit(5)
        return
    file.store_string(report)
    file.close()
    print("ROMA ROADS VISUAL: PASS screenshot=%s" % SCREEN)
    print(report)
    quit(0)
