extends SceneTree
## Fast one-time Terrain3D data bake.
## Python generates the proprietary control-map pixels vectorized; Godot only
## imports height + control images and saves the native Terrain3D region files.

const DATA_DIR := "res://terrain_data"
const CONTROL_PATH := "res://build/terrain_control.bin"
const READY_MARKER := DATA_DIR + "/READY.txt"
const RAW_PATH := "res://assets/heightmap.raw"
const MAP_SIZE_M := 2000.0
const HEIGHT_SCALE_M := 48.0
const BYTES_PER_SAMPLE := 2

var terrain: Terrain3D

func _init() -> void:
	call_deferred("_bake")

func _bake() -> void:
	if not ClassDB.class_exists("Terrain3D"):
		push_error("FAST TERRAIN BAKE: Terrain3D non disponibile")
		quit(10)
		return
	if not FileAccess.file_exists(RAW_PATH):
		push_error("FAST TERRAIN BAKE: RAW mancante")
		quit(11)
		return
	if not FileAccess.file_exists(CONTROL_PATH):
		push_error("FAST TERRAIN BAKE: control map mancante")
		quit(12)
		return

	terrain = Terrain3D.new()
	terrain.name = "Terrain3D_HEIGHTMAP_2000x2000"
	terrain.region_size = Terrain3D.SIZE_512
	terrain.vertex_spacing = MAP_SIZE_M / 1080.0
	terrain.mesh_lods = 7
	terrain.show_checkered = false
	terrain.show_colormap = false
	terrain.show_grey = false
	root.add_child(terrain, true)

	var roman_assets: Terrain3DAssets = load("res://terrain_materials/terrain_assets_roman_natural.tres")
	if roman_assets:
		terrain.assets = roman_assets
	terrain.material.auto_shader = false
	terrain.material.set_shader_param("macro_variation1", Vector3(0.985, 1.00, 0.96))
	terrain.material.set_shader_param("macro_variation2", Vector3(1.015, 1.00, 0.985))

	await process_frame
	if terrain.data == null:
		push_error("FAST TERRAIN BAKE: Terrain3D Data non inizializzato")
		quit(13)
		return

	var raw_bytes := FileAccess.get_file_as_bytes(RAW_PATH)
	if raw_bytes.size() % BYTES_PER_SAMPLE != 0:
		push_error("FAST TERRAIN BAKE: RAW 16-bit non valido")
		quit(14)
		return
	var samples := raw_bytes.size() / BYTES_PER_SAMPLE
	var side := int(sqrt(float(samples)))
	if side * side != samples:
		push_error("FAST TERRAIN BAKE: RAW non quadrato")
		quit(15)
		return

	var values := PackedFloat32Array()
	values.resize(samples)
	var min_u := 65535
	var max_u := 0
	for i in range(samples):
		var u := (int(raw_bytes[i * 2]) << 8) | int(raw_bytes[i * 2 + 1])
		if u < min_u:
			min_u = u
		if u > max_u:
			max_u = u
		values[i] = float(u)
	var source_range := maxf(1.0, float(max_u - min_u))
	for i in range(samples):
		values[i] = clampf((values[i] - float(min_u)) / source_range, 0.0, 1.0)

	var height_img := Image.create_from_data(side, side, false, Image.FORMAT_RF, values.to_byte_array())
	var control_bytes := FileAccess.get_file_as_bytes(CONTROL_PATH)
	if control_bytes.size() != samples * 4:
		push_error("FAST TERRAIN BAKE: control map dimensione errata")
		quit(16)
		return
	var control_img := Image.create_from_data(side, side, false, Image.FORMAT_RF, control_bytes)
	if height_img == null or control_img == null:
		push_error("FAST TERRAIN BAKE: impossibile creare mappe Terrain3D")
		quit(17)
		return

	var maps: Array[Image]
	maps.resize(Terrain3DRegion.TYPE_MAX)
	maps[Terrain3DRegion.TYPE_HEIGHT] = height_img
	maps[Terrain3DRegion.TYPE_CONTROL] = control_img
	terrain.data.import_images(maps, Vector3.ZERO, 0.0, HEIGHT_SCALE_M)
	terrain.data.calc_height_range(true)

	var abs_dir := ProjectSettings.globalize_path(DATA_DIR)
	DirAccess.make_dir_recursive_absolute(abs_dir)
	terrain.data.save_directory(DATA_DIR)
	await process_frame
	var marker := FileAccess.open(READY_MARKER, FileAccess.WRITE)
	if marker == null:
		push_error("FAST TERRAIN BAKE: impossibile creare READY.txt")
		quit(18)
		return
	marker.store_string("Terrain3D persistent data generated by vectorized CI bake.\n")
	marker.close()

	print("FAST TERRAIN BAKE OK regions=", terrain.data.get_region_locations().size())
	print("FAST TERRAIN BAKE min/max=", min_u, "/", max_u)
	quit(0)
